Update ONCAE scraper
open-contracting/kingfisher-collect pull request #495
Opened 2020-09-17 00:25 UTC by aguilerapy

closes #429

2020-09-17 00:31 UTC, aguilerapy commented
A new argument `system` was also added, which allows us to choose from which system the data will be taken.

2020-09-21 14:51 UTC, yolile requested changes

2020-09-21 14:51 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_oncae.py
> +                if next((system for system in systems_flags if not system), False):
@aguilerapy I find this a little bit hard to read, as `systems_flags` is a dict of booleans and as you are using `system` as variable name and there is a `self.system` variable too. Maybe it would be simpler to remove items from `self.systems` when you process a file for that system. eg: 
``` javascript
            if self.sample:
                # if we already downloaded a package for all the available systems
                if not self.systems:
                    return
                # if we already processed a file for the current system
                if current_system not in self.systems:
                    continue
                self.systems.remove(current_system)
```
or a set of downloaded_systems: 

``` javascript
        downloaded_systems = set()
        for url in urls:
            path, file = split(urlparse(url).path)
            current_system = path.replace('/datosabiertos/', "")
            if self.system and current_system != self.system:
                continue
            if self.sample:
                # if we already downloaded a package for all the available systems
                if downloaded_systems == self.systems:
                    return
                # if we already processed a file for the current system
                if current_system in downloaded_systems:
                    continue
                # add the current system to the set of downloaded_systems
                downloaded_systems.add(current_system)
```
and maybe you can rename `self.systems` to `available_systems`

2020-09-21 16:47 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_oncae.py
> +                if next((system for system in systems_flags if not system), False):
@aguilerapy I think that the second approach will be better as it doesn't remove items from the class variable, sorry!!

2020-09-22 13:23 UTC, yolile approved these changes

2020-09-22 13:24 UTC, merged