Add Zaragoza spider
open-contracting/kingfisher-collect pull request #510
Opened 2020-10-05 03:18 UTC by aguilerapy

closes #507

2020-10-05 14:34 UTC, yolile requested changes

2020-10-05 14:34 UTC, yolile commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            url = url + '&before={}&after={}'.format(before, after)
no debería ser al revés? before until_date and after from_date?

2020-10-05 14:34 UTC, yolile commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            before = self.from_date.strftime("%Y-%m-%d") + 'T00:00:00Z'
si el servicio acepta hora entonces el scraper también debería aceptar hora, usar el date_format = datetime

2020-10-05 14:34 UTC, yolile commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +    API documentation
es swagger

2020-10-05 17:44 UTC, aguilerapy commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            url = url + '&before={}&after={}'.format(before, after)
Si, debe ser al revés, pero creo que en el servicio esta así, [after=2020-10-05 y before=2000-01-01](https://www.zaragoza.es/sede/servicio/contratacion-publica/ocds/contracting-process/?rf=html&rows=100000&after=2020-10-05T14:37:22Z&before=2000-01-01T00:00:00Z) con datos, y [after=2000-01-01 y before=2020-10-05](https://www.zaragoza.es/sede/servicio/contratacion-publica/ocds/contracting-process/?rf=html&rows=100000&after=2000-01-01T00:00:00Z&before=2020-10-05T14:37:22Z) sin datos.

2020-10-05 17:56 UTC, aguilerapy commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            before = self.from_date.strftime("%Y-%m-%d") + 'T00:00:00Z'
hecho

2020-10-05 17:56 UTC, aguilerapy commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +    API documentation
hecho

2020-10-05 18:57 UTC, yolile submitted a review, later dismissed

2020-10-05 21:17 UTC, jpmckinney commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            url = url + '&before={}&after={}'.format(before, after)
Can you add a comment in the code, saying the `before` and `after` query string parameters behave opposite expectations? Otherwise, I'm sure a future reader will again ask the question.

2020-10-05 21:17 UTC, jpmckinney commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            url = self.url + contracting_process_id.get('id')
Why `get` and not `[]`? If the `id` key isn't set, then `get` returns `None`, and `str + None` is a more confusing error (TypeError) than if we used `[]` (KeyError).

2020-10-05 21:17 UTC, jpmckinney commented on kingfisher_scrapy/spiders/spain_zaragoza.py
> +            # A JSON array of ids strings
I don't see any JSON arrays of strings.

2020-10-06 17:50 UTC, yolile approved these changes

2020-10-06 17:51 UTC, merged