Add Nicaragua Solid Waste spider
open-contracting/kingfisher-collect pull request #511
Opened 2020-10-05 13:35 UTC by aguilerapy

closes #493

2020-10-05 14:14 UTC, yolile requested changes

2020-10-05 14:14 UTC, yolile commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +            url = self.url + '20130123/20130123'
could you use python string formatting instead of "+" ?

2020-10-05 14:16 UTC, yolile commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +                url = self.url + '20000101/20201231'
shouldn't the end date be set to today instead of hardcoding it?

2020-10-05 15:37 UTC, aguilerapy commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +            url = self.url + '20130123/20130123'
done.

2020-10-05 15:40 UTC, aguilerapy commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +                url = self.url + '20000101/20201231'
I added the spider attribute `date_required` to always get `from` and `until` dates.

2020-10-05 16:08 UTC, yolile requested changes

2020-10-05 16:08 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +    date_required = None
```suggestion
    date_required = False
```
and could you document this new attribute, please?

2020-10-05 16:08 UTC, yolile commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +            if self.from_date and self.until_date:
as `date_required` is set, this will always be true, right?

2020-10-05 17:29 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +    # Set `date_required` to True in class attribute to always set the `from` and `until` date parameters.
maybe add that if `date_required` is true the attribute `default_from_date` should be set too.

2020-10-05 17:29 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +        self.date_required = self.date_required
I think this is not needed

2020-10-06 11:55 UTC, yolile approved these changes

2020-10-06 14:39 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +    date_required = False
I think we can use `date_required` in PeriodicSpider and ParaguayDNCPBaseSpider, since `from_date` is required for those (and then we can remove or simplify `from_crawler` in each of those classes).

2020-10-06 14:44 UTC, jpmckinney commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +            url = url.format('20130123', '20130123')
Just curious - why this specific date?

2020-10-06 15:34 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +    date_required = False
yes! I thought the same, but I planned to create a new issue for that

2020-10-06 15:45 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +    date_required = False
Sure, it can be done in a new issue.

2020-10-06 16:18 UTC, aguilerapy commented on kingfisher_scrapy/spiders/nicaragua_solid_waste.py
> +            url = url.format('20130123', '20130123')
It's just the first date that I found useful for sample (one package with one release).

2020-10-06 19:44 UTC, merged