Add FlattenSpider and Bolivia Agetic spider
open-contracting/kingfisher-collect pull request #524
Opened 2020-10-19 16:26 UTC by aguilerapy

closes #490

2020-10-19 18:16 UTC, yolile requested changes

2020-10-19 18:16 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +        directory = 'tmp'
you should use https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory instead

2020-10-19 18:16 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +        basename, extension = os.path.splitext(response.request.url)
use `urlparse` instead see https://github.com/open-contracting/kingfisher-collect/commit/5276bab70df57e717b7cca106303ef6470f9929f about not using `os` related functions

2020-10-19 18:16 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +            else:
use elif instead

2020-10-19 18:16 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +import flattentool
update requirements to include flattentool library

2020-10-21 16:26 UTC, yolile requested changes

2020-10-21 16:26 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +                raise SpreadsheetExtensionError('The file has no extension or is not CSV or XLSX.')
as this is at the `parse` level I think it will better to yield a FileError instead of an exception, see an example https://github.com/open-contracting/kingfisher-collect/blob/0e09753856f9fab1d372c30fa07cdbaad8dc0e47/kingfisher_scrapy/spiders/chile_base.py#L55

2020-10-21 16:26 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +            file_path = directory + '/' + file_name
use `os.path.join` instead

2020-10-21 16:26 UTC, yolile commented on requirements.in
> +flattentool<=0.14
I think the problem with the flatten tool is fixed now so you can change this again https://github.com/OpenDataServices/flatten-tool/issues/363

2020-10-21 16:55 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +            if file_path.endswith('.csv'):
I think we can move this validation before creating the tmp file, as we actually need only `file_name` to validate the file extension.

2020-10-21 16:56 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +
we should probably also yield the original csv file, with `yield self.build_file_from_response(response, data_type=self.data_type, post_to_api=False, file_name=file_name)`

2020-10-21 18:10 UTC, aguilerapy commented on kingfisher_scrapy/base_spider.py
> +            if file_path.endswith('.csv'):
I'm sorry, before creating the tmp file or tmp directory?

Besides validating the file, `input_name` is set, which is used in `unflatten`, and that variable depends on the tmp directory.

2020-10-21 18:13 UTC, aguilerapy commented on kingfisher_scrapy/base_spider.py
> +            file_path = directory + '/' + file_name
This is not the same problem as https://github.com/open-contracting/kingfisher-collect/pull/524#discussion_r507965470?

2020-10-21 18:17 UTC, aguilerapy commented on kingfisher_scrapy/base_spider.py
> +                raise SpreadsheetExtensionError('The file has no extension or is not CSV or XLSX.')
`response.status` will be 200 in those cases, I need to add a more specific error message?

2020-10-21 18:25 UTC, aguilerapy commented on kingfisher_scrapy/base_spider.py
> +
done

2020-10-21 19:10 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +            if file_path.endswith('.csv'):
sorry I meant the tmp directory!

2020-10-21 19:17 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +                raise SpreadsheetExtensionError('The file has no extension or is not CSV or XLSX.')
yes, you can override the "errors" object with the http_code and maybe a "details" string https://github.com/open-contracting/kingfisher-collect/blob/0e09753856f9fab1d372c30fa07cdbaad8dc0e47/kingfisher_scrapy/spiders/chile_base.py#L53-L56

2020-10-21 19:23 UTC, yolile commented on kingfisher_scrapy/util.py
> +        if value.endswith('.json') or value.endswith('.xlsx'):
```suggestion
        if value.endswith(('.json', '.xlsx')):
```

2020-10-21 20:06 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +            file_path = directory + '/' + file_name
nop, as that comment was about URLs, in this case, as in Linux the paths are split with "/" but in Windows, they are splitter with "\" joining the path with the file with "/" will not work in Windows. see https://docs.python.org/3/library/os.path.html#module-os.path

2020-10-23 18:13 UTC, yolile commented
@jpmckinney do you want to review this as this is a base class addition?
What I realized is that we are writing the CSV and JSON files twice (the first one first in the temp directory and then by the file store extension, and the second one first by the flatten tool and then by the file store extension too). So I don't know if a better approach could be to use a pipeline instead, but then I realized that the file store is an extension and not a pipeline (not sure why), what do you think?

2020-10-23 19:31 UTC, jpmckinney reviewed
I think we maybe don't need a FlattenSpider class, just a new Flatten pipeline class.

To BaseSpider, we can add a class attribute `flatten = False`. Spiders that want to opt-in to the Flatten pipeline can set `flatten = True`. The Flatten pipeline would then process File items, modifying their data from CSV/XLSX data to JSON data. Would that work?

**Update:** It should be "unflatten" not "flatten".

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +    1. Set a ``ocds_version`` class attribute to the relevant schema version, '1.0' or '1.1' (default).
This is now documented in the BaseSpider class - we don't need to repeat it here.

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +    }
To avoid having to update this repo for new OCDS versions, use `get_tags` and `get_release_schema_url` from ocds-merge.

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +        file_name = urlsplit(response.request.url).path.split('/')[-1:][0]
Why `[-1:][0]` instead of:

```suggestion
        file_name = urlsplit(response.request.url).path.rsplit('/', 1)[-1]
```

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +            return
I think better to just raise a `NotImplementedError` with the detail as the message (after adding the filename and url to the message for context).

See #530 about constructing FileError items from spider exceptions.

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +        with tempfile.TemporaryDirectory() as directory:
As suggested, move the rest of the code to a pipeline class that modifies and returns an updated item.

In the spider, we just need to `build_file_from_response`, with maybe a new field to opt-in to the new pipeline class.

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +            return
Actually, this part can also be moved to the new pipeline class.

2020-10-23 19:31 UTC, jpmckinney commented on kingfisher_scrapy/spiders/bolivia_agetic.py
> +                break
I don't think we need this anymore.

2020-10-23 19:32 UTC, jpmckinney commented
I added some docs here, on what goes in pipelines versus extensions: https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#use-scrapy

2020-10-23 22:11 UTC, jpmckinney commented on kingfisher_scrapy/spiders/bolivia_agetic.py
> +        Downloads the first file in the downloads page.
Add new "Domain" term, documented here: https://kingfisher-collect.readthedocs.io/en/latest/spiders.html#spider-metadata

Also, put Spider arguments before Bulk download documentation (new order).

2020-10-23 22:11 UTC, jpmckinney commented on kingfisher_scrapy/spiders/bolivia_agetic.py
> +        Downloads the first file in the downloads page.
And there's a new `scrapy checkall` command to check docstrings, documented here: https://kingfisher-collect.readthedocs.io/en/latest/cli.html#checkall

2020-10-26 12:12 UTC, yolile commented
> I think we maybe don't need a FlattenSpider class, just a new Flatten pipeline class.
> 
> To BaseSpider, we can add a class attribute `flatten = False`. Spiders that want to opt-in to the Flatten pipeline can set `flatten = True`. The Flatten pipeline would then process File items, modifying their data from CSV/XLSX data to JSON data. Would that work?
> 
> **Update:** It should be "unflatten" not "flatten".

Yes, but we will still have the problem of saving the CSV and JSON files twice, once in the pipeline and then in the `KingfisherStoreExtension`

2020-10-26 13:05 UTC, jpmckinney commented
I don’t see that as a problem: writing files in the spider is a bigger problem (a blocking operation in the Scrapy engine).

A workaround is to change the storage extension to move the files instead of rewriting them if a path is provided.

2020-11-03 00:31 UTC, aguilerapy commented
It's necessary to update requirements file for `ocdsmerge`? Checks didn't fail.

2020-11-03 16:21 UTC, yolile commented
> It's necessary to update requirements file for ocdsmerge? Checks didn't fail.

Yes, it is

2020-11-03 16:56 UTC, yolile commented on kingfisher_scrapy/pipelines.py
> +            for i in range(1, len(tags)):
you can do something like:
```           
            spider_ocds_version = spider.ocds_version.replace('.', '__')
            for tag in reversed(tags):
                if spider_ocds_version in tag:
                    schema = get_release_schema_url(tag)
                    break
```
to avoid using indexes

2020-11-03 16:57 UTC, yolile commented
@jpmckinney now we are using a pipeline but only the converted JSON file is being stored, not the original CSV. Is that the expected output?

2020-11-03 17:31 UTC, jpmckinney commented on kingfisher_scrapy/pipelines.py
> +                input_name = file_path
Move this outside the `with` block, so that the `with` block is just focused on I/O.

2020-11-03 17:31 UTC, jpmckinney commented on kingfisher_scrapy/pipelines.py
> +            with open(file_path, 'r') as f:
Have you tested with XLSX? I would have expected the mode would have to be `rb`.

2020-11-03 17:31 UTC, jpmckinney commented on kingfisher_scrapy/base_spider.py
> +       in the Unflatten pipeline class using the  ``unflatten`` command from Flatten Tool.
```suggestion
       in the Unflatten pipeline class using the ``unflatten`` command from Flatten Tool.
```

2020-11-03 17:31 UTC, jpmckinney commented on kingfisher_scrapy/pipelines.py
> +                item['file_name'] = components(-1)(item['file_name']) + '.json'
What is this doing? In what case does the filename contain multiple components? Also, will the filename be using filesystem path separators or URL path separators?

2020-11-03 17:31 UTC, jpmckinney commented on kingfisher_scrapy/pipelines.py
> +                return item
```suggestion
        return item
```

2020-11-03 17:31 UTC, jpmckinney commented on tests/__init__.py
> +    request = Request('http://example.com' + url_path, meta=meta)
```suggestion
    request = Request(f'http://example.com{url_path}', meta=meta)
```

2020-11-03 17:31 UTC, jpmckinney commented on tests/pipelines/test_unflatten.py
> +def test_process_item():
Please add a test that succeeds with an xlsx file.

2020-11-03 17:33 UTC, jpmckinney commented on kingfisher_scrapy/pipelines.py
> +            for i in range(1, len(tags)):
```python
            spider_ocds_version = spider.ocds_version.replace('.', '__')
            for tag in reversed(get_tags()):
                if tag.startswith(spider_ocds_version):
                    schema = get_release_schema_url(tag)
                    break
```

Using `startswith` instead of `in` prevents `ocds_version = '1.1'` from matching both `1.1.0` and `2.1.1`.

We also want this to be a `for-else` statement, where the `else` raises an exception because no schema was found.

And we should have this outside the `with` block, so that we error early before writing the temporary file.

2020-11-03 17:34 UTC, jpmckinney commented
> @jpmckinney now we are using a pipeline but only the converted JSON file is being stored, not the original CSV. Is that the expected output?

I think having a consistent output format (JSON) is good for users. If there is user demand, I guess we could offer a way to write the CSV/XLSX file directly – though if users really want CSVs, we probably want an optional Flatten pipeline that can be used with all existing spiders. In we were to add that pipeline, we'd add a special case so that the Unflatten pipeline is skipped if the user opted into the Flatten pipeline.

2020-11-10 16:06 UTC, yolile commented on kingfisher_scrapy/pipelines.py
> +        if not spider.unflatten:
```suggestion
        if not spider.unflatten or not isinstance(item, (File, FileItem)):
```

2020-11-10 20:34 UTC, jpmckinney approved these changes

2020-11-11 12:33 UTC, yolile approved these changes

2020-11-11 12:33 UTC, merged