Add Civic Data Lab India spider
open-contracting/kingfisher-collect pull request #567
Opened 2020-11-25 01:46 UTC by aguilerapy

closes #494

2020-11-25 15:55 UTC, yolile commented
@aguilerapy could you run `scrapy updatedocs`?  This command should be run every time we add a new spider https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#commit-the-spider

2020-11-26 11:55 UTC, yolile requested changes

2020-11-26 11:55 UTC, yolile commented on kingfisher_scrapy/spiders/india_civic_data_lab.py
> +    data_type = 'release_list'
Hmm, this should be release_package, shouldn't it? Same for bolivia_agetic actually

2020-12-16 15:45 UTC, aguilerapy commented on kingfisher_scrapy/spiders/india_civic_data_lab.py
> +    data_type = 'release_list'
Done for Bolivia and India.

2020-12-16 15:46 UTC, aguilerapy commented
I added the possibility to give more arguments to `unfflaten` with the `unflatten_args` class attribute.

2020-12-17 12:46 UTC, yolile requested changes

2020-12-17 12:46 UTC, yolile commented on kingfisher_scrapy/spiders/india_civic_data_lab.py
> +                yield scrapy.Request(
can we just:

```python
                yield self.build_request(
                    f'https://github.com{path}?raw=true',
                    formatter=components(-1)
                )
```
?
same for Bolivia actually. 

and then in https://github.com/open-contracting/kingfisher-collect/blob/2380f96531630aa203c7db9a188a5d2d3d6a1f50/kingfisher_scrapy/base_spider.py#L190

```python       
 if not file_name.endswith(('.json', '.zip', '.xlsx', '.csv')):
````

2020-12-17 19:19 UTC, aguilerapy commented on kingfisher_scrapy/spiders/india_civic_data_lab.py
> +                yield scrapy.Request(
Done.

2020-12-21 16:27 UTC, yolile approved these changes

2020-12-21 16:27 UTC, merged