Implement date spider arguments
open-contracting/kingfisher-collect pull request #596
Opened 2021-01-15 16:41 UTC by aguilerapy

ref #346

2021-01-18 12:25 UTC, yolile commented on kingfisher_scrapy/spiders/colombia_bulk.py
> +                if not (self.from_date.year <= int(url[-8:-4]) <= self.until_date.year):
please put `int(url[-8:-4])` in a separate variable and comment the URL format

2021-01-18 12:25 UTC, yolile commented on kingfisher_scrapy/spiders/dominican_republic.py
> +                    if not (self.from_date.year <= int(url[-8:-4]) <= self.until_date.year):
please put int(url[-8:-4]) in a separate variable and comment the URL format

2021-01-18 12:46 UTC, yolile reviewed
@jpmckinney here, for some spiders (`afghanistan_*`, `costa_rica`, `malta` and `zambia`), we are omitting the "base" URL and using directly the URL format that the base list has. This can lead to some 404 errors. Not sure if this is ok or we should filter the base list instead.

Eg if the base list: `['something/releases/2021-01-01', 'something/releases/2021-01-15' ]` and
`from_date = 2021-01-01` and `default_until_date = today`

without using the base_list =  2 200 responses and 16 404 responses

using the base_list = 2 200 responses

but I'm not sure if this is really a problem.

2021-01-18 15:37 UTC, jpmckinney commented
I think it's better to use the base list. We use the log to determine how "clean" a collection was, and the 404 errors would normally indicate a less clean collection.

2021-01-18 15:42 UTC, yolile requested changes
@aguilerapy please see the comments above

2021-02-09 17:13 UTC, aguilerapy commented on kingfisher_scrapy/spiders/colombia_bulk.py
> +                if not (self.from_date.year <= int(url[-8:-4]) <= self.until_date.year):
done

2021-02-09 17:13 UTC, aguilerapy commented on kingfisher_scrapy/spiders/dominican_republic.py
> +                    if not (self.from_date.year <= int(url[-8:-4]) <= self.until_date.year):
done

2021-02-09 17:13 UTC, aguilerapy commented
> @aguilerapy please see the comments above

Done.

2021-02-09 17:22 UTC, jpmckinney commented
@aguilerapy Since I merged #572, there are now some conflicts to resolve.

2021-02-12 11:45 UTC, yolile commented on kingfisher_scrapy/base_spider.py
> +    VALID_DATE_FORMATS = {'date': '%Y-%m-%d', 'datetime': '%Y-%m-%dT%H:%M:%S', 'year': '%Y', 'year-month': '%Y-%m'}
@aguilerapy could you also update the docs at 
https://github.com/open-contracting/kingfisher-https://github.com/open-contracting/kingfisher-collect/blob/671db55ae2336ac900100bd885cceccb8deb75c2/kingfisher_scrapy/base_spider.py#L27-L31 please?

2021-02-12 11:46 UTC, yolile commented on kingfisher_scrapy/spiders/afghanistan_releases.py
> +            yield self.build_request(url, formatter=components(-2))
@aguilerapy why -2 now?

2021-02-12 11:56 UTC, yolile commented on kingfisher_scrapy/spiders/dominican_republic.py
> -        json_urls = list(filter(lambda x: '/JSON' in x, urls))
@aguilerapy we already support now rar and zip files in the same spider, but we can implement 2020 in another PR as it has a different pattern

2021-03-01 14:16 UTC, aguilerapy commented on kingfisher_scrapy/base_spider.py
> +    VALID_DATE_FORMATS = {'date': '%Y-%m-%d', 'datetime': '%Y-%m-%dT%H:%M:%S', 'year': '%Y', 'year-month': '%Y-%m'}
done

2021-03-01 14:17 UTC, aguilerapy commented on kingfisher_scrapy/spiders/afghanistan_releases.py
> +            yield self.build_request(url, formatter=components(-2))
changed to 1 again

2021-03-01 14:23 UTC, aguilerapy commented on kingfisher_scrapy/spiders/dominican_republic.py
> -        json_urls = list(filter(lambda x: '/JSON' in x, urls))
ok!

2021-03-03 13:35 UTC, yolile commented
@aguilerapy is this ready for review again now?

2021-03-15 19:56 UTC, yolile requested changes
@aguilerapy could you please add an URL example for all the URLs that you are parsing, please?

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/afghanistan_releases.py
> -            # A JSON array of URL strings, in reverse chronological order.
I think that we should keep these comments

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/chile_compra_bulk.py
> +    default_from_date = '2009-01'
these ones are from # BaseSpider

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/chile_compra_bulk.py
> +    # PeriodicSpider variables
```suggestion
    # PeriodicSpider
```

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/colombia_bulk.py
> +          Sistema Electrónico para la Contratación Pública (plataforma exclusivamente de publicidad)
No estoy segura de a qué te referís con "exclusivamente de publicidad"?

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/malta.py
> +                year = int(url[82:86])
maybe it is better to start and the end instead of the beginning? eg `url[-6:-2]` or maybe just `url.split('/')[-2]` and url.split('/')[-1] ?

2021-03-15 19:56 UTC, yolile commented on kingfisher_scrapy/spiders/malta.py
> +                year = int(url[82:86])
and please move `# URL looks like http://malta-demo-server.eurodyn.com/ocds/services/recordpackage/getrecordpackage/2020/1 here`

2021-03-17 22:32 UTC, aguilerapy commented on kingfisher_scrapy/spiders/malta.py
> +                year = int(url[82:86])
done with split()

2021-03-17 22:32 UTC, aguilerapy commented on kingfisher_scrapy/spiders/colombia_bulk.py
> +          Sistema Electrónico para la Contratación Pública (plataforma exclusivamente de publicidad)
corregido

2021-03-17 22:32 UTC, aguilerapy commented on kingfisher_scrapy/spiders/chile_compra_bulk.py
> +    default_from_date = '2009-01'
done

2021-03-17 22:32 UTC, aguilerapy commented on kingfisher_scrapy/spiders/afghanistan_releases.py
> -            # A JSON array of URL strings, in reverse chronological order.
done

2021-03-17 22:42 UTC, aguilerapy commented
> @aguilerapy could you please add an URL example for all the URLs that you are parsing, please?

Sorry, I'm not sure I understand, add where?

2021-03-17 23:02 UTC, yolile commented
I mean a comment in each place where you are parsing a URL, with a comment
similar to the malta one " The URL looks like.."

El mié., 17 de marzo de 2021 7:42 p. m., aguilerapy <
***@***.***> escribió:

> @aguilerapy <https://github.com/aguilerapy> could you please add an URL
> example for all the URLs that you are parsing, please?
>
> Sorry, I'm not sure I understand, add where?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-contracting/kingfisher-collect/pull/596#issuecomment-801489072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABUEPSUZPAJCIMGYKQNMDETTEEV47ANCNFSM4WEJ3URQ>
> .
>

2021-03-18 16:57 UTC, yolile commented on kingfisher_scrapy/spiders/malta.py
> +                # URL looks like http://malta-demo-server.eurodyn.com/ocds/services/recordpackage/getrecordpackage/
@aguilerapy could you add this type of comment to each URL you are parsing in each spider? This is for making it easier for another developer to understand the code.

2021-03-18 16:57 UTC, yolile commented on kingfisher_scrapy/spiders/colombia_bulk.py
>          SECOP1
@aguilerapy it seems that you are missing an indentation here?

2021-03-29 23:53 UTC, yolile approved these changes

2021-03-29 23:54 UTC, yolile commented
@jpmckinney do you want to review this too?

2021-03-30 00:29 UTC, jpmckinney commented
I'll have a look.

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/spiders/costa_rica_poder_judicial_records.py
> +                    # .json
Avoid breaking the URL across lines

```suggestion
                    # URL looks like:
                    # https://pjcrdatosabiertos.blob.core.windows.net/datosabiertos/OpenContracting/2021.json
```

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/spiders/dominican_republic.py
> +                            continue
We can just search for the first four digits with the regex. Also, do any URLs not match? If all should match, we should omit the if-statement, as it will just hide a future bug.

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/spiders/malta.py
> +                # 2020/1
```suggestion
                # URL looks like:
                # http://malta-demo-server.eurodyn.com/ocds/services/recordpackage/getrecordpackage/2020/1
```

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/spiders/malta.py
> +                month = int(url.split('/')[-1])
Split once (also for Zambia)

```suggestion
                year, month = map(int, url.rsplit('/', 2)[1:])
```

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/spiders/malta.py
> +                        and (self.from_date.month <= month <= self.until_date.month)):
I don't think this works (also for Zambia)

```
year, month = 2020, 3
from_year, from_month = 2019, 6
until_year, until_month = 2021, 1
from_month <= month <= until_month  # i.e. 6 <= 3 <= 1
# False, but 2020 is definitely between 2019 and 2021...
```

2021-03-31 23:32 UTC, jpmckinney commented on kingfisher_scrapy/util.py
> +        yield (start + timedelta(days=days)).strftime('%Y-%m-%d')
Why does this method yield strings? `date_range_by_month` yields dates.

2021-04-05 13:41 UTC, yolile commented on kingfisher_scrapy/spiders/dominican_republic.py
> +                            continue
All the URLs match, I will change it to search for the 4 digits and remove the if

2021-04-05 15:05 UTC, yolile commented on kingfisher_scrapy/util.py
> +        yield (start + timedelta(days=days)).strftime('%Y-%m-%d')
Actually, I think that we are not using this method anywhere so I will delete it cc @aguilerapy

2021-04-06 19:43 UTC, jpmckinney approved these changes

2021-04-06 20:17 UTC, merged