673 indonesia
open-contracting/kingfisher-collect pull request #676
Opened 2021-03-18 22:16 UTC by cecicasco

closes #673

2021-03-18 22:47 UTC, yolile requested changes
@cecicasco Congratulations on coding your first spider! I just left a couple of comments. And also please don't forget to run `scrapy updatedocs` https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#commit-the-spider

2021-03-18 22:47 UTC, yolile commented on kingfisher_scrapy/spiders/indonesia_opentender.py
> +        date = response.request.meta['date']
I think that instead of modifying the base calls we can do something like this: (get the year from the request URL)
```suggestion
        year = parameters('year')(response.request.url).split('-')[1]
```

2021-03-18 22:47 UTC, yolile commented on kingfisher_scrapy/spiders/indonesia_opentender.py
> +            code = item['code']
I tested this and I got some request duplication warnings, which mean that we are having duplicates in the response, so we can do something like 
```python
        requested_codes = set()
        for item in data['data']:
            code = item['code']
            # there are some duplicated codes
            if code and code not in requested_codes:
                requested_codes.add(code)
               ....
```

2021-03-19 12:33 UTC, yolile commented on kingfisher_scrapy/spiders/indonesia_opentender.py
> +    default_from_date = '2020'
@cecicasco should this be 2008?

2021-03-19 12:57 UTC, yolile commented on kingfisher_scrapy/spiders/indonesia_opentender.py
> +            if code not in requested_codes:
In the previous version, you checked if `code` is not `None`  so I assume that is still needed?
```suggestion
            if code and code not in requested_codes:
```

2021-03-19 12:59 UTC, cecicasco commented on kingfisher_scrapy/spiders/indonesia_opentender.py
> +            if code not in requested_codes:
I gonna add again, you are right..

2021-03-19 13:14 UTC, yolile approved these changes

2021-03-19 13:16 UTC, merged