Add link to bulk downloads
open-contracting/kingfisher-collect pull request #715
Opened 2021-05-10 19:13 UTC by cecicasco

closes #703

2021-05-10 20:11 UTC, yolile commented on kingfisher_scrapy/spiders/georgia_records.py
> +    Bulk download documentation
@jpmckinney just checking if this is what you wanted or https://odapi.spa.ge/publication-policy directly

2021-05-10 20:30 UTC, jpmckinney commented on kingfisher_scrapy/spiders/georgia_records.py
> +    Bulk download documentation
https://odapi.spa.ge/spage.json.zip is a link to a bulk download, not to "bulk download documentation". So,  https://odapi.spa.ge/publication-policy is more appropriate.

2021-05-10 20:45 UTC, yolile requested changes

2021-05-10 20:45 UTC, yolile commented on docs/spiders.rst
> +Test
?

2021-05-10 20:45 UTC, yolile commented on kingfisher_scrapy/spiders/georgia_records.py
> +    Bulk download documentation
@cecicasco please change the docs to https://odapi.spa.ge/publication-policy

2021-05-10 20:52 UTC, cecicasco commented
perfect

2021-05-11 17:21 UTC, yolile approved these changes

2021-05-12 13:14 UTC, yolile commented
@cecicasco actually, could you add the same documentation to `georgia_releases` too?

2021-05-12 20:25 UTC, yolile approved these changes

2021-05-12 20:25 UTC, merged