706 mexico izai
open-contracting/kingfisher-collect pull request #759
Opened 2021-07-09 12:58 UTC by cecicasco

Closes #706

2021-07-09 17:53 UTC, yolile commented
@cecicasco I think that this PR includes also the `739_mexico_quien_es_quien_records` branch changes, so can you start another one or remove those changes from this PR? thanks

2021-07-09 17:54 UTC, cecicasco commented
> @cecicasco I think that this PR includes also the `739_mexico_quien_es_quien_records` branch changes, so can you start another one or remove those changes from this PR? thanks
 OK! I gonna check it.. thanks

2021-07-09 17:58 UTC, yolile requested changes

2021-07-09 17:58 UTC, yolile commented on kingfisher_scrapy/spiders/mexico_izai.py
> +    name = 'mexico_izai'
let's name it as the other INAIs eg `mexico_zacatecas_izai`, also for the class name and file name, see `mexico_durango_idaip` for an example

2021-07-09 18:16 UTC, yolile commented on kingfisher_scrapy/spiders/mexico_zacatecas_izai.py
> +class MexicoZacatecasIZAI(PeriodicSpider):
```suggestion
class MexicoZacatecas(PeriodicSpider):
```

2021-07-09 18:16 UTC, yolile commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_zacatecas_izai.MexicoZacatecasIZAI
```suggestion
.. autoclass:: kingfisher_scrapy.spiders.mexico_zacatecas_izai.MexicoZacatecas
```

2021-07-12 15:26 UTC, yolile commented
@cecicasco FYI the mexico changes are still in this branch and PR

2021-07-14 19:25 UTC, closed without merging