add nigeria ebonyi state spider
open-contracting/kingfisher-collect pull request #772
Opened 2021-08-04 21:51 UTC by Ravf95

Closes #746

2021-08-04 22:57 UTC, yolile requested changes

2021-08-04 22:57 UTC, yolile commented on kingfisher_scrapy/spiders/nigeria_ebonyi_state.py
> +      Ebonyi E-PROCUREMENT
@Ravf95 could you run `scrapy checkall --loglevel=WARNING` as documented [here](https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#commit-the-spider), to ensure you are documenting the `from_date` and `until_date` parameters? you can see `mexico_durango_idaip` as example

2021-08-05 13:35 UTC, Ravf95 commented on kingfisher_scrapy/spiders/nigeria_ebonyi_state.py
> +      Ebonyi E-PROCUREMENT
I fix it in the next commit. I take `from_date` and `until_date` from the bulk download list of
https://ebonyieprocure.eb.gov.ng/ocds_report.php

2021-08-05 14:59 UTC, yolile approved these changes

2021-08-05 15:04 UTC, merged