add nigeria cross river state spider
open-contracting/kingfisher-collect pull request #774
Opened 2021-08-04 22:45 UTC by Ravf95

Closes #766

2021-08-04 23:07 UTC, yolile requested changes

2021-08-04 23:07 UTC, yolile commented on kingfisher_scrapy/spiders/nigeria_cross_river_records.py
> +    API documentation
same as the other we should add the Spider arguments for `from_date` and `until_date`

2021-08-04 23:07 UTC, yolile commented on kingfisher_scrapy/spiders/nigeria_cross_river_base.py
> +    default_until_date = '2020-11'
how do you know these are the default dates?

2021-08-05 13:36 UTC, Ravf95 commented on kingfisher_scrapy/spiders/nigeria_cross_river_records.py
> +    API documentation
I fix it in the next commit

2021-08-05 13:40 UTC, Ravf95 commented on kingfisher_scrapy/spiders/nigeria_cross_river_base.py
> +    default_until_date = '2020-11'
I take `from_date` and `until_date` from the monthly download list of
http://ocds.dppib-crsgov.org/ReleasePackageViewModel_ListView/

2021-08-05 14:57 UTC, yolile requested changes

2021-08-05 14:57 UTC, yolile commented on kingfisher_scrapy/spiders/nigeria_cross_river_base.py
> +    default_until_date = '2020-11'
Then, instead of implementing this as a `PeriodicSpider`, I think that we should get the list of the available dates from that page. Right now the spider will try to get the data for all the months from February to November, but I see in that list that there are some unavailable months, as May, July, September, etc. So we should a) Document ttp://ocds.dppib-crsgov.org/ReleasePackageViewModel_ListView/ as "Bulk download documentation" and b) Reimplement the spider to get the available months and years from there.

2021-08-06 15:50 UTC, Ravf95 commented
Yes! We can try to obtain the available dates of the page, it would take more time because it is a page programmed with ASP.NET and it is more complex to scrape it, I did not do it like that due to the priority of the issue.
We should also think about pagination, currently, we only have one page of results but in the future, we could have more, should I implement this functionality now anyway? I won't be able to test it

2021-08-06 17:03 UTC, yolile commented
Hmm, ok, so let's merge this now (you will need to resolve the conflict files) but please open a new issue to fix it later.

2021-08-08 14:11 UTC, yolile approved these changes

2021-08-08 14:11 UTC, merged