update honduras portal bulk spider
open-contracting/kingfisher-collect pull request #804
Opened 2021-09-24 22:22 UTC by Ravf95

Ref #414

2021-09-28 15:54 UTC, yolile requested changes

2021-09-28 15:54 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +        if publisher and spider.publisher not in spider.available_publishers.keys():
```suggestion
        if publisher and spider.publisher not in spider.available_publishers:
```
.keys() is the default behavior

2021-09-28 15:54 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +            if spider.system not in spider.available_systems.keys():
```suggestion
            if spider.system not in spider.available_systems:
```

.keys() is the default behavior

2021-09-28 15:54 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +            date = datetime(int(item['year']), int(item['month']), 1)
You can move this inside the if block, as the date is only needed if the from_date and until_date are set

2021-09-28 15:54 UTC, yolile commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +        for item in response.json():
Could you add a comment on how each item looks so it is easier for another developer to understand the code and filters? eg 
``` python
# "Each item looks like:  {
#    "urls": {
#      "csv": "...",
#      "md5": "...",
#      "json": "...",
#      "xlsx": "..."
#    },
#    "year": "2012",
#    "month": "01",
#    "sistema": "Sistema de Informacion Financiero Integrado v2.0",
#    "publicador": "Secretaria de Finanzas de Honduras"
#  }

2021-09-28 16:15 UTC, Ravf95 commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +        if publisher and spider.publisher not in spider.available_publishers.keys():
Yes, you're right!. I will remove it on the next commit

2021-09-28 16:15 UTC, Ravf95 commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +            if spider.system not in spider.available_systems.keys():
Yes, you're right!. I will remove it on the next commit

2021-09-28 16:15 UTC, Ravf95 commented on kingfisher_scrapy/spiders/honduras_portal_bulk.py
> +        for item in response.json():
Yes, I will add a comment

2021-10-01 01:44 UTC, yolile approved these changes

2021-10-01 01:54 UTC, merged