Update Mexico INAI's spiders
open-contracting/kingfisher-collect pull request #846
Opened 2021-10-27 19:43 UTC by aguilerapy

closes #819

2021-11-08 13:56 UTC, yolile commented
@aguilerapy FYI Just in case, I left some comments on this PR some days ago

2021-11-16 13:43 UTC, aguilerapy commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
For the spider naming convention, I think this should be 'mexico_mexico_city_info'.

2021-11-16 13:45 UTC, aguilerapy commented on kingfisher_scrapy/spiders/mexico_inai_base.py
> +    fiscal_years_api = 'edca/fiscalYears'
done!

2021-11-16 13:45 UTC, aguilerapy commented on kingfisher_scrapy/spiders/mexico_inai_base.py
> +    contracts_api = 'edca/contractingprocess/{}'
done!

2021-11-16 13:50 UTC, aguilerapy commented on kingfisher_scrapy/spiders/mexico_inai_base.py
> +            self.domain_pattern.format(self.fiscal_years_api),
done!

2021-11-16 13:50 UTC, aguilerapy commented on kingfisher_scrapy/spiders/mexico_inai_base.py
> +            yield self.build_request(self.domain_pattern.format(self.contracts_api.format(fiscal_year)),
done!

2021-11-16 13:52 UTC, yolile commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
That is not what we agreed on https://github.com/open-contracting/kingfisher-collect/pull/820#issuecomment-934723132 same for `MexicoMexicoStateINFOEM`

2021-11-16 13:54 UTC, aguilerapy commented on kingfisher_scrapy/spiders/mexico_inai_base.py
> +    #. Set a ``domain_pattern`` class attribute to assign the portal domain with {} in the end of the string
done!

2021-11-16 14:02 UTC, aguilerapy commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
Is the same case as in [#820 (comment)](https://github.com/open-contracting/kingfisher-collect/pull/812#issuecomment-933582521). Should be just 'info', not 'infocdmx'.

2021-11-16 14:15 UTC, yolile commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
I don't think it is the same case. INFOCDMX and INFOEM are indeed acronymous of these institutions, so it is ok to use them (as IAIP for Oaxaca). "INFO" is nothing for Mexico City and Mexico State, that is why we agreed to use those names in that PR. @jpmckinney what do you think?

2021-11-16 14:33 UTC, aguilerapy commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
I understand that "INFO" is an autonomous organ, and there are several "INFO"s in all of Mexico:

- https://www.infocdmx.org.mx/
- https://www.infoem.org.mx/
- http://infocol.org.mx/
- https://www.ceigqro.org.mx/

2021-11-16 14:41 UTC, yolile commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
Yes, but their full acronym is INFOCDMX, INFOEM, INFOCOL, etc, INFO alone doesn't mean anything. For Oaxaca, we actually conserved the acronym (IAIP see their logo at https://iaipoaxaca.org.mx/site/) and just removed the extra O (from Oaxaca)

2021-11-16 14:54 UTC, aguilerapy commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
It's a bit confusing, [here](https://drive.google.com/file/d/1T_OtYiS2KkRfduva27pXZbGwHWImHP4g/view) the logo is just INFO for INFOCDMX, but [here](https://drive.google.com/file/d/1bnruT3uUeLteP4vzVqZj6XMTLzquSD1I/view) is INFOEM. 

Also [here](http://www.infocdmx.org.mx/index.php/nuestro-instituto/%C2%BFqu%C3%A9-es-el-infodf.html), INFOCDMX is referring just to INFO.

2021-11-16 14:55 UTC, jpmckinney commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
Like @yolile explained, http://www.idaipqroo.org.mx and https://iaipoaxaca.org.mx/ use both the IDAIP and IDAIPQROO, and IAIP and IAIPO acronyms. You can see the shorter acronym in their logos, for example. Since the extra QROO and O just duplicate the subdivision name, we prefer the shorter acronym.

With INFOCDMX, etc. it's true that CDMX, EM, COL duplicate the subdivision name, but these publishers never use INFO on its own.

The primary goal of the naming convention is to make it easy for users to identify which spider they want. If we use an acronym that is never used, that makes it harder for them to identify the spider. Keeping the spider name short and non-duplicative is a secondary goal.

2021-11-16 15:33 UTC, yolile commented on docs/spiders.rst
> +.. autoclass:: kingfisher_scrapy.spiders.mexico_mexico_city_info.MexicoMexicoCityINFO
> Also here, INFOCDMX is referring just to INFO.

I asked Tony and he thinks INFOCDMX is clearer.

2021-11-18 13:59 UTC, yolile requested changes
@aguilerapy I think the only missing change is to rename Mexico CIty back to MexicoMexicoCityINFOCDMX and INFOEM back to INFOEM and re-run the `updatedocs` command

2021-11-18 16:40 UTC, yolile submitted a review, later dismissed

2021-11-18 16:43 UTC, yolile approved these changes

2021-11-18 16:49 UTC, merged