update india_civic_data_lab spider
open-contracting/kingfisher-collect pull request #856
Opened 2021-11-04 17:04 UTC by Ravf95

Closes #821

2021-11-04 20:08 UTC, yolile requested changes

2021-11-04 20:08 UTC, yolile commented on kingfisher_scrapy/spiders/india_civic_data_lab.py
> +            raise Exception()
```suggestion
            raise KingfisherScrapyError('Truncated results returned when querying the file list from GitHub')
```

2021-11-04 20:08 UTC, yolile commented on kingfisher_scrapy/spidermiddlewares.py
> +           raise exception
FYI @jpmckinney I added this to the `RetryDataErrorMiddleware` otherwise the spider's exceptions are not raised!

2021-11-04 20:16 UTC, jpmckinney commented on kingfisher_scrapy/spidermiddlewares.py
> +           raise exception
Oh, right! Did you check any other `process_spider_exception` handlers for the same problem?

2021-11-04 20:22 UTC, yolile commented on kingfisher_scrapy/spidermiddlewares.py
> +           raise exception
Yes, and this is the only `process_spider_exception` handler we have so far so this change should be enough

2021-11-05 17:44 UTC, yolile commented
@jpmckinney let me know if it looks good for you now

2021-11-05 20:46 UTC, jpmckinney approved these changes

2021-11-08 13:47 UTC, merged