add italy anac spider
open-contracting/kingfisher-collect pull request #872
Opened 2021-11-24 19:55 UTC by Ravf95

Closes #867

2021-11-24 20:41 UTC, yolile requested changes
This is a CKAN site, therefore you can do something similar to what is done in `argentina_buenos_aires`, `costa_rica_poder_judicial_records`, and others (see more at #404). I see that we can use https://dati.anticorruzione.it/opendata/api/3/action/package_search?q=ocds to list all of the OCDS related resources.

2021-11-25 15:10 UTC, Ravf95 commented
Thanks for the suggestion. I changed the base class to request that endpoint.

2021-11-26 14:02 UTC, yolile commented on kingfisher_scrapy/spiders/italy_anac.py
> +       Italy ANAC
```suggestion
       Autorità Nazionale Anticorruzione
```

2021-11-26 14:03 UTC, yolile commented on kingfisher_scrapy/spiders/italy_anac.py
> +       Autorità Nazionale Anticorruzione
```suggestion
       Autorità Nazionale Anticorruzione (ANAC)
```

2021-11-26 16:12 UTC, yolile approved these changes

2021-11-26 19:59 UTC, merged