add mexico puebla itaip spider
open-contracting/kingfisher-collect pull request #884
Opened 2021-12-20 14:24 UTC by Ravf95

Closes #840

2021-12-20 15:22 UTC, yolile requested changes

2021-12-20 15:22 UTC, yolile commented on kingfisher_scrapy/spiders/mexico_puebla_itaip.py
> +class MexicoPueblaITAIP(MexicoINAIBase):
I think the name should be ITAIPUE? https://itaipue.org.mx/ similar to mexico_infoem where we use the full path including the repetition to make it closer to the acronym used by the users, see the note in https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#choose-a-spider-name. And please rename everything accordingly, thanks!

2021-12-20 16:59 UTC, Ravf95 commented on kingfisher_scrapy/spiders/mexico_puebla_itaip.py
> +class MexicoPueblaITAIP(MexicoINAIBase):
Thanks, I will apply the suggestion in the next comit!

2021-12-21 12:57 UTC, yolile approved these changes

2021-12-21 12:57 UTC, merged