united_kingdom_contracts_finder: update to download record packages
open-contracting/kingfisher-collect pull request #919
Opened 2022-04-05 19:26 UTC by Ravf95

Closes #917

2022-04-05 21:48 UTC, yolile requested changes

2022-04-05 21:48 UTC, yolile commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder.py
> +                    yield scrapy.Request(url, meta={'file_name': f'{ocid}.json'}, callback=super().parse)
I suggest you keep this method as it is now and create a new one, for example, `build_urls` (you will need to set the `parse_list_callback` class variable to 'build_urls') and you will need to check for `self.is_http_success(response)` in this new method as well, in case the request fails here. And per https://github.com/open-contracting/kingfisher-collect/issues/917#issuecomment-1089394438 we will need to have two spiders, one for the releases and another one for the records. So you might want to create a base class.
And I assume by iterating the search endpoint we will have some duplicated ocids, so maybe we can implement a logic to avoid that or we can let scrapy drop the duplicated requests. @jpmckinney what do you think?

2022-04-05 21:53 UTC, jpmckinney commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder.py
> +                    yield scrapy.Request(url, meta={'file_name': f'{ocid}.json'}, callback=super().parse)
Let Scrapy drop the duplicate requests.

2022-04-05 21:54 UTC, Ravf95 commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder.py
> +                    yield scrapy.Request(url, meta={'file_name': f'{ocid}.json'}, callback=super().parse)
Thanks, I suggest we can use UnitedKingdomContractsFinder as a base class for the new spider (keeping parse list), and for the new one, we can implement a logic to avoid/replace the duplicated files.

2022-04-06 15:11 UTC, Ravf95 commented
I close this PR to send a new one.

2022-04-06 15:11 UTC, closed without merging