add united_kingdom_contracts_finder_records spider
open-contracting/kingfisher-collect pull request #920
Opened 2022-04-06 16:32 UTC by Ravf95

Closes #917

2022-04-06 16:36 UTC, Ravf95 commented
@yolile @jpmckinney I checked the [isort documentation](https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html) but I don't understand why the check fails

2022-04-06 16:40 UTC, jpmckinney commented
Just run `isort . --line-width 119` to fix it.

2022-04-06 22:01 UTC, yolile requested changes

2022-04-06 22:01 UTC, yolile commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder_records.py
> +        for result in response.json()['results']:
We need to check here if the response was successful and if not, apply the same existing logic. So, instead of overriding the parse method, I would suggest adding a new one that checks if the response was successful, build the URLs, and then callback the parse method. Same for the releases spider that also needs to build the URLs.

2022-04-08 16:55 UTC, Ravf95 commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder_releases.py
> +class UnitedKingdomContractsFinderReleases(UnitedKingdomContractsFinderBase):
Done

2022-04-08 16:56 UTC, Ravf95 commented on kingfisher_scrapy/spiders/united_kingdom_contracts_finder_records.py
> +        for result in response.json()['results']:
Done

2022-04-08 19:24 UTC, yolile commented
I've refactored the code a little bit to avoid some duplications. @jpmckinney not sure if we should do something else or different to improve this further

2022-04-08 19:25 UTC, yolile submitted a review, later dismissed

2022-04-08 20:12 UTC, jpmckinney approved these changes

2022-04-08 20:24 UTC, merged